[build]
  publish = "public"
  command = "hugo -s ."

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.55.5"

[context.production.environment]
  HUGO_BASEURL = "https://dumping.guide/"

[context.deploy-preview]
  command = "hugo -s . -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deplpy]
  command = "hugo -s . -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"

